(() => {
const $=id=>document.getElementById(id),KEY='drago-arena-v2',API=window.DRAGO_API_URL||'https://dragobott.onrender.com';
const base={name:'Герой Драго',level:1,xp:0,coins:0,wins:0,attack:14,defense:4,maxHp:100,hp:100,potions:3,loot:[]};let state={...base,...JSON.parse(localStorage.getItem(KEY)||'{}')},enemy=null,user=null,serverUpgrades={};
const foes=[['Гоблін-крадій','👺',55,8,1,18,18,'🪙 Мішечок монет'],['Крижаний вовк','🐺',75,11,2,28,25,'❄️ Крижане ікло'],['Темний лицар','🗡️',105,15,5,48,36,'🛡️ Темний щит'],['Вогняний дракон','🐲',150,20,7,80,55,'🔥 Луска дракона']];
function local(){localStorage.setItem(KEY,JSON.stringify(state))}function save(){local();if(!user)return;fetch(API+'/api/user/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({telegramId:user.id,username:user.username||'',firstName:user.first_name||state.name,money:state.coins,playerLevel:state.level,playerXP:state.xp,upgrades:{...serverUpgrades,arena:state}})}).catch(()=>{})}
async function sync(){if(!user)return;try{const r=await fetch(API+'/api/user/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({telegramId:user.id,username:user.username||'',firstName:user.first_name||state.name})});if(!r.ok)throw Error();const d=await r.json();serverUpgrades=d.upgrades||{};if(d.upgrades?.arena)state={...base,...d.upgrades.arena};else {state.coins=Math.max(state.coins,d.money||0);state.level=Math.max(state.level,d.playerLevel||1);state.xp=Math.max(state.xp,d.playerXP||0);save()}render();log('☁️ Прогрес синхронізовано з базою даних.')}catch{log('⚠️ Офлайн: прогрес поки збережений лише на пристрої.')}}
function bar(id,v,m){$(id).style.width=Math.max(0,Math.min(100,v/m*100))+'%'}function render(){['hero-name','player-name'].forEach(id=>$(id).textContent=state.name);$('hero-level').textContent='Рівень '+state.level;$('coins').textContent=state.coins;$('wins').textContent=state.wins;$('stat-atk').textContent=state.attack;$('stat-def').textContent=state.defense;$('stat-hp').textContent=state.maxHp;$('potions').textContent=state.potions;$('xp').textContent=state.xp+' / '+state.level*100+' XP';bar('xp-bar',state.xp,state.level*100);$('player-hp-text').textContent='❤️ '+state.hp+' / '+state.maxHp;bar('player-hp',state.hp,state.maxHp);if(enemy){$('enemy-name').textContent=enemy.name;$('enemy-emoji').textContent=enemy.icon;$('enemy-hp-text').textContent='❤️ '+enemy.hp+' / '+enemy.maxHp;bar('enemy-hp',enemy.hp,enemy.maxHp)}$('loot-list').innerHTML=state.loot.length?state.loot.slice(-8).reverse().map(x=>'<div>'+x+'</div>').join(''):'<p>Поки що порожньо. Перемагай ворогів!</p>';local()}function log(s){$('battle-log').textContent=s}
function telegram(){user=window.Telegram?.WebApp?.initDataUnsafe?.user||null;if(user){state.name=user.first_name||state.name;window.Telegram.WebApp.expand();$('avatar').src=user.photo_url||'https://api.dicebear.com/7.x/adventurer/svg?seed='+user.id}else $('avatar').src='https://api.dicebear.com/7.x/adventurer/svg?seed=drago'}
function spawn(){let f=foes[Math.min(3,Math.floor((state.level-1)/2)+Math.floor(Math.random()*2))],m=1+(state.level-1)*.16;enemy={name:f[0],icon:f[1],maxHp:Math.round(f[2]*m),hp:Math.round(f[2]*m),atk:Math.round(f[3]*m),def:Math.round(f[4]*m),reward:f[5],xp:f[6],loot:f[7]};$('attack').disabled=false;$('heal').disabled=false;log(enemy.name+' виходить на арену!');render()}function gain(x){state.xp+=x;while(state.xp>=state.level*100){state.xp-=state.level*100;state.level++;state.maxHp+=18;state.attack+=3;state.defense++;state.hp=state.maxHp;state.potions++;log('🎉 Новий рівень!')}}function attack(){if(!enemy)return;let h=Math.max(1,state.attack+Math.floor(Math.random()*7)-enemy.def);enemy.hp-=h;if(enemy.hp<=0){state.coins+=enemy.reward;state.wins++;state.loot.push(enemy.loot);gain(enemy.xp);log('🏆 Перемога! +'+enemy.reward+' 🪙, +'+enemy.xp+' XP');enemy=null;$('attack').disabled=true;$('heal').disabled=true;render();save();return}let b=Math.max(1,enemy.atk+Math.floor(Math.random()*5)-state.defense);state.hp-=b;if(state.hp<=0){state.hp=state.maxHp;enemy=null;$('attack').disabled=true;$('heal').disabled=true;log('💥 Герой відновився.')}else log('Ти завдав '+h+' шкоди. '+enemy.name+' відповідає: -'+b+' HP.');render();save()}function heal(){if(!enemy||!state.potions||state.hp===state.maxHp)return;state.potions--;state.hp=Math.min(state.maxHp,state.hp+Math.round(state.maxHp*.35));log('✨ Зілля відновило здоров’я.');render();save()}function upgrade(){if(state.coins<50)return log('Потрібно 50 🪙.');state.coins-=50;state.attack+=2;state.defense++;state.maxHp+=10;state.hp=state.maxHp;log('⬆️ Герой покращений!');render();save()}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab],.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')});$('new-enemy').onclick=spawn;$('attack').onclick=attack;$('heal').onclick=heal;$('upgrade').onclick=upgrade;telegram();render();sync();})();
